In [1]:
import pandas as pd
import numpy as np

In [8]:
def weighted_jacc(list1, list2):
    # Obtain counts from each set:
    A = pd.Series(list1).value_counts()
    B = pd.Series(list2).value_counts()
    
    df1 = pd.DataFrame({'x':A, 'y':B})
    
    # Replace missing values in df1 with 0:
    sad = df1.fillna(0)
    min_col = sad.min(axis=1)
    max_col = sad.max(axis=1)
    # Compute and return numerator/denominator:
    return np.sum(min_col) / np.sum(max_col)

In [9]:


l1 = ['apple', 'apple', 'orange', 'durian', 'durian', 'mango']
l2 = ['apple', 'orange', 'orange', 'durian']

print(weighted_jacc(l1, l2))
print(3/7)

0.42857142857142855
0.42857142857142855


In [ ]:
liverpool = pd.read_csv("liverpool_2223_season.csv")
# print(liverpool.iloc[0:5, 3:])
print(liverpool.loc[0:4, 'GF':'Opponent'])
print(liverpool.iloc[0:5, 3:6])


   GF  GA        Opponent
0   2   2          Fulham
1   1   1  Crystal Palace
2   1   2  Manchester Utd
3   9   0     Bournemouth
4   2   1   Newcastle Utd
   GF  GA        Opponent
0   2   2          Fulham
1   1   1  Crystal Palace
2   1   2  Manchester Utd
3   9   0     Bournemouth
4   2   1   Newcastle Utd


'2.3.3'

In [15]:
x = np.zeros((2,2))
y = np.zeros((2,1))

np.hstack((x,y))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
wip = pd.read_csv("wip.txt", sep=" ")

wip.groupby('plant').describe()

AttributeError: 'DataFrameGroupBy' object has no attribute 'info'

In [25]:
from scipy import stats

student = pd.read_csv("student-mat.csv", sep=";")
table = pd.crosstab(student.address, student.guardian)
chisq_output = stats.chi2_contingency(table)
print(f"The p-value is {chisq_output.pvalue:.3f}.")
print(f"The test-statistic value is {chisq_output.statistic:.3f}.")
chisq_output.expected_freq

The p-value is 0.263.
The test-statistic value is 2.675.


array([[ 20.05063291,  60.82025316,   7.12911392],
       [ 69.94936709, 212.17974684,  24.87088608]])

In [26]:
import numpy as np
x = np.array([[1],
              [0],
              [-2]])
y = np.array([[0.3],
              [-0.9],
              [0.3]])

np.matmul(np.reshape(x, (1,3)), y)

array([[-0.3]])

In [ ]:
def recurse(x):
    if x == 1:
        return 0
    if x == 2:
        return 1
    return 2 * recurse(x-1) - recurse(x-2)

res = []
for i in range(1, 31):
    res.append(recurse(i))
print(sum(res))


435
